### ISSUE TITLE
"Horizontal navigation" tweak causes clicking anywhere on a user's profile to go to the previous page

### ISSUE THREAD

**Issue by garcia** [enchanted-sword/ch-utils#7]
**Describe the bug**
After clicking the "next page" button on a profile, clicking anywhere resets it to the previous page.

**To Reproduce**
1. Go to any cohost profile page with multiple pages of posts, e.g. https://cohost.org/jkap
2. Click the "next page" button at the bottom
3. Click anywhere on the page
4. The page resets to the previous page of posts

**Expected behavior**
Page should stay the same

**Screenshots**
n/a

**Device information (please complete the following information):**
 - OS: Windows 10
 - Version: Firefox 126

**Additional context**
This happens if you click the "previous page" button as well, but the outcome is not reversed, it still specifically decrements the page on click. For example:

1. You are on page=3
2. You click the "previous page" button, taking you to page=2
3. You click anywhere on the page, causing it to go to page=1

**Comment by enchanted-sword** [comment]
looks like the pagination button hyperlinks have a solitary hashtag at the end for some reason, which was causing them to get filtered by the code that normally adds functionality to the bookmarked tags button on the dashboard. i'm not sure why that module was even set up to run on project pages in the first place, but both bugs should be fixed in f637468.
